lint:
  command: npm run lint
  description: Run lint
lint-fix:
  command: npm run lint-fix
  description: Run lint, but fix any findings
arguments:
  commands:
    - ls $1
    - ps $2
    - echo $1 $1
  description: Do a test with argument replacement
multi:
  commands:
    - sleep 1
    - ls -la
  description: Do a test with multiple commands
error:
  commands:
    - thisShouldError
    - ls -la
  description: Test that an error in one command will stop commands
newversion:
  commands:
    - npm --no-git-tag-version version $1
    - npm install
  description: Update the package.json with a new version
version:
  command: npm view ubolt version
  description: Show the current version of the package
gitbranch:
  command: echo "$GITBRANCH"
  description: Show the current git branch
  options:
    usesGitBranch: true
